### ISSUE TITLE
Adicionar recurso de `/campaign`

### ISSUE THREAD

**Issue by hiwllc** [arrecadar/api-express#14]
Adicionar as seguintes rodas:

- [x] `GET /campaigns` lista todas as campanhas criadas paginada, exibindo 10 resultados por vez.
- [x] `GET /campaigns/:id` lista apenas a campanha selecionada, deve conter as informações da ONG.
- [x] `POST /campaigns` adiciona uma nova campanha.
- [x] `PUT /campaigns/:id` edita uma campanha.
- [x] `DELETE /campaign/:id` remove uma campanha.

**Comment by hiwllc** [comment]
@flyingluscas @guuibayer podem adicionar observações e dúvidas se vocês tiverem 😊 .

**Comment by iamgbayer** [comment]
Poderíamos mapear já os possíveis atributos de uma campanha além de uma ONG? Assim já temos uma ideia de como vai ser seu Schema

**Comment by hiwllc** [comment]
Como assim @guuibayer eu criei o model de campanha aqui: https://github.com/arrecadar/api/blob/475880c0757ae6af1357f8038256a8f4ef77ef0e/app/Campaigns/model.js#L4 mas não tenho certeza se é exatamente isso (lembrando que estamos falando de um MVP)
