### ISSUE TITLE
Autenticação

### ISSUE THREAD

**Issue by hiwllc** [arrecadar/api-express#15]
O fluxo de autenticação e autorização deverá ser:

- [x] E-mail e Senha.
- [x] A navegação deverá ser feita via token (possívelmente via jwt).

**Comment by iamgbayer** [comment]
Quão seria interessante utilizar uma rede social como Facebook para a autenticação? Apenas observando um pouco, vi que varias ONG's utilizam o mesmo já.

**Comment by hiwllc** [comment]
Isso vai entrar no roadmap, mas no momento por questões de simplicidade vamos manter apenas com email e senha, login social pode entrar depois do alpha.

**Comment by hiwllc** [comment]
Pra criar a autenticação, vamos criar um módulo separado usando o passport, está sendo desenvolvido nesse link: [anarklab/expressive-passport](https://github.com/anarklab/expressive-passport)
