### ISSUE TITLE
Erro com docker environment

### ISSUE THREAD

**Issue by hiwllc** [arrecadar/api-express#30]
- [x] **Bug** report

### Comportamento esperado:
Deveria conectar no mongodb corretamente.

### Comportamento atual:
- Váriaveis definidas no `.env` não foram replicadas no ambiente do Heroku.
- Ao subir o container local, não conecta ao localhost.
- Algumas dependencias não estão sendo instaladas no `docker`

### Descrição do erro:
O erro ocorre ao tentar conectar com o mongodb, como não existe nas váriaveis de ambiente acaba tendo esse erro, além disso os erros acima causam um blocker no desenvolvimento.

### Passos para reproduzir
só rodar no terminal: `heroku logs --app arrecadar-org --tail`

**Comment by flyingluscas** [comment]
@uselessdev estou confuso com esta issue, me parece ser dois problemas em uma issue só, consegue deixar mais claro o que está acontecendo?
