### ISSUE TITLE
Dúvida se devemos permitir exclusão de campanha e ong

### ISSUE THREAD

**Issue by hiwllc** [arrecadar/api-express#33]
No momento é possível excluir Campanha e Ongs, queria saber se realmente precisamos disso e SE podemos permitir que isso ocorra, talvez desativar apenas seria uma opção.

**Comment by iamgbayer** [comment]
Acho que desativar seria uma melhor opção, levando em conta que também um pouco já relacionado é de devermos ter um sistema de report para aquelas que quebrem nossos termos e politicas e desativando a mesma.
